//! Data-only projection for existing Tier2 reducers and viewers. No Tier1 rules.
pub const SCHEMA: &str = r#"
; Shared rule-combination templates: no concrete values, event IDs or Entry.
(datatype RuleId (Rule String))
(sort LocalPort)
(sort RelativeBinding)
(sort PartialPort)
(sort PartialRelativeBinding)
(sort Comb)
(sort ParentCombs)
(constructor ParentPort (i64 i64 String) LocalPort)
(constructor Make (String RelativeBinding String) LocalPort)
(constructor RNil () RelativeBinding)
(constructor RCons (LocalPort RelativeBinding) RelativeBinding)
(constructor Local (LocalPort) PartialPort)
(constructor External (i64 String) PartialPort)
(constructor MakePartial (String PartialRelativeBinding String) PartialPort)
(constructor PNil () PartialRelativeBinding)
(constructor PCons (PartialPort PartialRelativeBinding) PartialRelativeBinding)
(constructor Empty () Comb)
(constructor SmoothRuleComposition (ParentCombs RuleId RelativeBinding) Comb)
(constructor CoarseRuleComposition (ParentCombs RuleId PartialRelativeBinding) Comb)
(constructor NoParents () ParentCombs)
(constructor MoreParents (Comb ParentCombs) ParentCombs)
; Occurrences and their evidence are a separate layer, never children of Comb.
(datatype Val (V String String))
(datatype Args (ANil) (ACons Val Args))
; RowFact identifies one committed row version (or one exact boundary row).
; Its opaque token is not an expression subject to EqAt rewriting.
(datatype Effect (HasFact String Args) (Equal Val Val) (RowFact Val))
(datatype Effects (ENil) (ECons Effect Effects))
(datatype Instance (Occurrence i64 Comb))
(relation ParentAt (Instance i64 Instance))
(relation OutputAt (Instance i64 Val))
(relation ExternalAt (Instance i64 Val))
(relation ExternalFact (Instance Effect))
(relation Produced (Instance Effect))
(relation Requires (Instance Effects))
(relation ParentTemplate (Comb i64 Comb))
(relation LinkedParent (Instance i64 Instance))
(relation Binding (Instance Args))
(relation Provides (Instance Effect))
(relation SupportsUse (Instance Instance))
"#;
